Remove setting represent_boolean_as_integer in the dummy app
This was deprecated and is now removed in Rails 6.1. This was
causing:

NoMethodError:
  undefined method `represent_boolean_as_integer=' for nil:NilClass